// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_HC8QWJXwYRGO_91QX1WmDE7ZNr55FA',
    appId: '1:768804098620:web:4afd219e69d823c290e939',
    messagingSenderId: '768804098620',
    projectId: 'solarsystem-120a0',
    authDomain: 'solarsystem-120a0.firebaseapp.com',
    storageBucket: 'solarsystem-120a0.appspot.com',
    measurementId: 'G-TC9VX0XHRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsYuFtoebvEtVd0sccDEgtuK5fqKlQJDI',
    appId: '1:768804098620:android:8377ec132d35fa1a90e939',
    messagingSenderId: '768804098620',
    projectId: 'solarsystem-120a0',
    storageBucket: 'solarsystem-120a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuDjrE0-b715UgwiVxgvecjOUsyRmNYVI',
    appId: '1:768804098620:ios:1e35a13676ac4a4e90e939',
    messagingSenderId: '768804098620',
    projectId: 'solarsystem-120a0',
    storageBucket: 'solarsystem-120a0.appspot.com',
    iosClientId: '768804098620-2enk5mi54giopfl0je8k2bkonf5gqhnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuDjrE0-b715UgwiVxgvecjOUsyRmNYVI',
    appId: '1:768804098620:ios:1e35a13676ac4a4e90e939',
    messagingSenderId: '768804098620',
    projectId: 'solarsystem-120a0',
    storageBucket: 'solarsystem-120a0.appspot.com',
    iosClientId: '768804098620-2enk5mi54giopfl0je8k2bkonf5gqhnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarsystem',
  );
}
